### ISSUE TITLE
Test xblock-google-drive on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/xblock-google-drive#86]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

- [ ] Requirements are compiled with Python 3.8
- [ ] Tests are run on Python 3.8 and 3.11
- [ ] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.
- [ ] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support
- [ ] A new version is release to PyPI
- [ ] A PR is merged to edx-platform to use the new version

**Comment by Agrendalath** [comment]
@feanil, I auto-closed this issue by merging the linked PR. If I understand this correctly, `v0.7.0` should be pulled automatically into `edx-platform` by the requirements bot. Please let me know if we should keep this issue open until then.
